# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6a0407e95093bddd0fead20bba5a20e700bd1ad4f87df19a5388cc8f204102ac1ede692753af304cf2d777900c1c1bc38334712120b82f87f4d5efa778c845d

test:
  secret_key_base: 9c8398ad48e14f7c331c7b032aa206e8c66e1ea08fe33dfd64bfe4c1858ae1b3a8a1964d92929b447fea4950cd1cc89edcf361f284f06206acdbcf7d9aed15f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
